### ISSUE TITLE
Apple Store rejection due to non-public API

### ISSUE THREAD

**Issue by kftomita** [benbahrenburg/ti.mely#13]
Hi,
Recently I tried to publish an app, and Apple store rejected it saying that it was accessing a non public API, called 'defaultConfig'. Since the app doesn't call any non-public API, Apple sad that, if the app, or its modules, call a similar name to 'defaultConfig', this is enough to reject the app. 
So, the variables that I found on my app are:
defaultConfigurationIsVisible
defaultConfigurationName

Those are ti.mely variables. Would be possible to change those names to not interfere on the Apple publication process?

Thanks,
Katia

**Comment by benbahrenburg** [comment]
I don't think ti.mely has those values anywhere in the source.  Can you send me the line number you are referencing?

**Comment by kftomita** [comment]
Thanks for your answer.
This is the info that I got when looking for 'defaultConfig' on the build:
iphone/Aim2Act.xcodeproj/project.pbxproj:3147:	defaultConfigurationIsVisible = 0;
iphone/Aim2Act.xcodeproj/project.pbxproj:3148:	defaultConfigurationName = Release;
iphone/Aim2Act.xcodeproj/project.pbxproj:3156:	defaultConfigurationIsVisible = 0;
iphone/Aim2Act.xcodeproj/project.pbxproj:3157:	defaultConfigurationName = Release;

I will follow your suggestion and rebuild the project with an upgraded version of Xcode.
